### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by BePsvPT** [Sunday-Without-God/Juice#7]
- [ ]  exam 的 submission 要能看到是誰交的
- [ ]  /submission/:id/code 如果是用上傳檔案的方式交上去的 得到的值會是暫存檔的路徑
- [ ]  post /exams 的 question info 驗證規則 長度限制改為 4 允許 goal 跟 reward 為 null
- [ ]  /exams 回傳的結果要該判斷使用者是這場考試的管理 or 助教 以及參加者
